services:
  typescript:
    image: typescript
    build:
      context: node_modules/typescript
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
